notes =
{
	love.audio.newSound("sounds/"),
	love.audio.newSound("sounds/"),
	love.audio.newSound("sounds/"),
	love.audio.newSound("sounds/"),
	love.audio.newSound("sounds/"),
	love.audio.newSound("sounds/"),
	love.audio.newSound("sounds/"),
	love.audio.newSound("sounds/"),
	love.audio.newSound("sounds/"),
	love.audio.newSound("sounds/"),
	love.audio.newSound("sounds/"),
	love.audio.newSound("sounds/"),
	love.audio.newSound("sounds/"),
	love.audio.newSound("sounds/"),
	love.audio.newSound("sounds/"),
	love.audio.newSound("sounds/"),
}
